name: ai_avatar_mobile
description: "AI Avatar Video Mobile App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  video_player: ^2.7.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  flutter_cache_manager: ^3.3.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
