# render.yaml - Configuration file for deploying to Render.com
services:
  - type: web
    name: ai-avatar-video
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: sqlite:///app.db
    healthCheckPath: /
    disk:
      name: data
      mountPath: /opt/render/project/src/app/storage
      sizeGB: 1
