name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Render
        uses: renderinc/render-action@v1
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}  # Add this in GitHub repository secrets
          
      - name: Verify Deployment
        run: |
          echo "Deployment to Render triggered!"
          echo "Check your Render dashboard for deployment status."
